server:
  port: 9090

spring:
  datasource:
    url: jdbc:postgresql://java12postgre/MovieAppDockerDB
    username: postgres
    password: hakan
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

      #url: jdbc:postgresql://localhost:5432/MovieAppDockerDB
      #url: jdbc:postgresql://java12postgre/MovieAppDockerDB
